### ISSUE TITLE
Reverse proxy limitations

### ISSUE THREAD

**Issue by yuvadm** [andrewgodwin/daphne#4]
What limitations exist for running daphne behind a reverse proxy such as:
- nginx
- apache
- AWS ELB
- haproxy
- heroku routing layer (nginx, probably)

Can daphne be used as an (almost) drop in replacement for e.g. gunicorn?

**Comment by andrewgodwin** [comment]
As far as I am aware there are no reverse proxy limitations; Daphne will function just like gunicorn (in fact, that's what it's roughly modelled after).

The one problem you may run into is that some reverse proxies don't support WebSocket (HTTP/1.1 UPGRADE), which would stop that from working, but my understanding is that all the ones you posted can now be made to.

**Comment by yuvadm** [comment]
cool, thanks!

**Comment by gipi** [comment]
One functionality that seems missing is the possibility to bind the server to an unix socket, like ``gunicorn``. This is kind of blocking for some deployment.

I don't know if this is by design.

**Comment by andrewgodwin** [comment]
It's mostly because I don't use unix sockets for proxying anymore, going for TCP instead, but it's something that could be added - I'll add it to the upcoming list of things-people-can-work-on.

**Comment by k4ml** [comment]
What about the timeout settings in server such as nginx ?

>By default, the connection will be closed if the proxied server does not transmit any data within 60 seconds. This timeout can be increased with the proxy_read_timeout directive. Alternatively, the proxied server can be configured to periodically send WebSocket ping frames to reset the timeout and check if the connection is still alive.

http://nginx.org/en/docs/http/websocket.html

Should this being handled by daphne, like by sending the ping as mentioned in nginx doc above ? For now I have to do a [reconnect](https://github.com/devkini/mychat/commit/7fe7938f2e686e64d101a421ca766ffed55bc51e).

Maybe something like this - https://github.com/gorilla/websocket/blob/master/examples/chat/conn.go#L71

**Comment by andrewgodwin** [comment]
Yes, that's an excellent point, Daphne should do pings by default. I'll get it in now.

**Comment by andrewgodwin** [comment]
Daphne `0.10.1` now does pings as a keepalive after a socket has been idle for a while; 20 seconds by default, but configurable with ``--ping-interval``.

**Comment by helderco** [comment]
I can't setup an nginx reverse proxy in the front of daphne, what should the nginx config be?

proxy_pass? uwsgi_pass?

```
server {
    server_name _;
    listen [::]:80;

    location / {
        proxy_pass http://daphne;

        # HTTP 1.1 support
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $proxy_connection;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
    }
}
```

PS: using docker.

**Comment by andrewgodwin** [comment]
proxy_pass, just follow standard WebSocket load balancing guides. Your config looks alright - what's the error you got? Did you expose the right port on the daphne container and make it listen on port 80?

**Comment by helderco** [comment]
No output when looking at the logs. From the nginx container I try to do a `curl http://daphne` but it just waits for a response.

```
version: '2'

services:
  web:
    image: nginx:stable-alpine
    ports:
      - 80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  daphne:
      build: .
      ports:
        - 80
      command: daphne -b 0.0.0.0 -p 80 confs.asgi:channel_layer
      working_dir: /usr/src/app/src
      depends_on:
        - redis
      env_file:
        - prod.env
```
